### ISSUE TITLE
feed() and detect() take &Vec<u8> and not a slice &[u8]

### ISSUE THREAD

**Issue by raphaelcohn** [thuleqaid/rust-chardet#1]
This means that if I feed `detect()` using a `BufReader`, I have to make a clone of the bytes to feed into `detect()`...

Would you consider changing this API to take a slice? Or perhaps a Into<Cow<Vec<u8>>?

**Comment by thuleqaid** [comment]
thank you for your advice. i'd add/change the api in the weekend.
