### ISSUE TITLE
UTF-8 occasionally misdetected as ISO-8859-1

### ISSUE THREAD

**Issue by vojtechkral** [thuleqaid/rust-chardet#6]
I've written a simple tool for checking encoding of codebases and I've noticed `chardet` sometimes detects UTF-8 as ISO-8859-1. The most minimal such example is:

    °C

In hex:

    00000000: c2b0 43

Both the `file` as well as the `uchardet` utilities report this as UTF-8 text.

**Comment by thuleqaid** [comment]
The following hex is acceptable for both ISO-8859-1 and UTF-8.
```
00000000: c2b0 43
```

In [ISO-8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1), the above hex can be translated into following text:
```
Â°C
```

One cannot determine which coding is the correct one when both coding can correctly decode the hex.

[chardet](https://chardet.readthedocs.io/en/latest/faq.html) use a different algorithm from uchardet, it calculates the confidence of UTF-8(0.505) and ISO8859-1(0.73), so it reports ISO-8859-1. By appending extra text(e.g a Chinese character), UTF-8 will be reported.
```
00000000: c2b0 43e4 b8ad
```
